// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWd-JvsYiX05knYquteK1s3ojPEnYK5rI',
    appId: '1:851484123579:android:a9ec3df946dd7e3a61649e',
    messagingSenderId: '851484123579',
    projectId: 'relations-2ea0e',
    databaseURL: 'https://relations-2ea0e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'relations-2ea0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0MF_H8DwWl691bRD8mz_n7j_xwxoXym8',
    appId: '1:851484123579:ios:280707949916f2d861649e',
    messagingSenderId: '851484123579',
    projectId: 'relations-2ea0e',
    databaseURL: 'https://relations-2ea0e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'relations-2ea0e.appspot.com',
    iosClientId: '851484123579-b53k9i03ou3c9pp4g4j6q4d517ql6ldr.apps.googleusercontent.com',
    iosBundleId: 'com.example.relations',
  );
}
